version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nutri-system-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri_pass
      POSTGRES_DB: nutri_system
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

  app:
    build: .
    container_name: nutri-system-app
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
